# -*- coding: utf-8 -*-
"""522HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kZploOPtjlQUl3eB1mPTN3Tnpf-msKs
"""

def add(a, b):
    return a + b

print("3 + 5 =", add(3, 5))